"""
THE HUSHABALOO -- block manifest.

The single source of truth. `tools/generate.py` reads this to produce audio and word
timings; `player/index.html` addresses the same block IDs via `data-audio`. If an ID
here has no counterpart in the player (or the reverse), `tools/audit.py` fails the build
-- that mismatch is exactly how DATATRAX's karaoke silently desynced.

Block kinds
-----------
speech  Narration or dialogue. Sent to ElevenLabs TTS with character-level timestamps,
        which are aggregated to words for the karaoke highlight.
sfx     A sound effect, generated from `text` as a prompt. No words, no highlighting.
wait    A participation beat: the player pauses so the listeners can make the sound
        themselves. Never blocks -- it always auto-advances (see PARTICIPATION below).

Voice tags in square brackets ([excited], [whispers]) are performance direction for
eleven_v3. They are stripped before word timings are matched to the DOM, so they must
never appear in the player's visible text.
"""

# ── Cast ──────────────────────────────────────────────────────────────────────
# Resolved from .env at generation time; these names are the contract.
VOICES = {
    "NARRATOR":   "VOICE_NARRATOR",
    "ETTA":       "VOICE_ETTA",
    "KIP":        "VOICE_KIP",
    "MO":         "VOICE_MO",
    "HUSHABALOO": "VOICE_HUSHABALOO",
}

# ── Performance settings ──────────────────────────────────────────────────────
# eleven_v3 treats `stability` as a performance dial, not a quality one:
#   0.0 Creative  -- follows inline [direction] hardest, widest emotional range
#   0.5 Natural   -- balanced, stays recognisably the same person
#   1.0 Robust    -- flat and consistent, largely ignores direction
#
# The narrator speaks roughly two thirds of the book and has to swing from a
# barely-there whisper on spread 7 to headlong joy on spread 8, so it runs
# Creative. The children and the Hushabaloo sit at Natural: they appear in short
# bursts and need to sound like the same character every time.
# PITCH is applied after generation by tools/master_voices.py, in semitones.
# The library has no child voices (and v3 will not design one), so the children are
# adult character voices lifted into a child register -- which is how animation has
# always cast children. Kip goes higher than Mo on purpose: the twins have to stay
# separable by ear, and pitch is the cheapest axis to hold them apart on.
PITCH_SEMITONES = {"ETTA": 2.0, "KIP": 4.0, "MO": 2.5}

VOICE_SETTINGS = {
    "NARRATOR":   {"stability": 0.0, "similarity_boost": 0.75, "style": 0.6,  "use_speaker_boost": True},
    "ETTA":       {"stability": 0.0, "similarity_boost": 0.8,  "style": 0.70, "use_speaker_boost": True},
    "KIP":        {"stability": 0.0, "similarity_boost": 0.8,  "style": 0.80, "use_speaker_boost": True},
    "MO":         {"stability": 0.0, "similarity_boost": 0.8,  "style": 0.60, "use_speaker_boost": True},
    "HUSHABALOO": {"stability": 0.3, "similarity_boost": 0.75, "style": 0.50, "use_speaker_boost": True},
    "_default":   {"stability": 0.5, "similarity_boost": 0.75, "style": 0.4,  "use_speaker_boost": True},
}

# ── Pauses (seconds of silence appended after a block) ────────────────────────
LINE = 0.6      # between blocks inside a thought
BEAT = 1.2      # a landed beat
SECTION = 1.8   # between speakers
PAGE = 2.5      # end of a spread

# ── Sound effects ─────────────────────────────────────────────────────────────
# Generated once each and reused by every block that references them. CLICK is
# deliberately one file used three times -- spread 1, spread 9's payoff, and the last
# line -- because the listener must recognise it as literally the same sound.
#
# `peak_dbfs` feeds the startle guard in tools/mix.py. Nothing here may exceed the
# narration RMS by more than +6 dB, and everything gets a >=30 ms attack.
SFX = {
    # source="cc0"  -> fetched by tools/fetch_sfx.py from The Designer's Choice UCS
    #                  Collection (public domain), then trimmed, fade-shaped and
    #                  loudness-normalised. tools/generate.py leaves these alone.
    # source="gen"  -> generated by ElevenLabs from `prompt`.
    #
    # `lufs` is the mastering target and is what actually enforces the startle
    # spec in research/03-audio-sfx-and-elevenlabs.md: quieter targets for the
    # beds, louder for the moments meant to land, nothing sharp enough to jolt.

    # -- real Foley, because a real door and a real raspberry beat a described one --
    "click":           dict(source="cc0", seconds=1.4, lufs=-20),
    "creak":           dict(source="cc0", seconds=2.5, lufs=-21),
    "pop":             dict(source="cc0", seconds=2.2, lufs=-19),
    "rain":            dict(source="cc0", seconds=6.0, lufs=-24),
    "room_tone":       dict(source="cc0", seconds=8.0, lufs=-30),
    "bell":            dict(source="cc0", seconds=2.5, lufs=-22),
    "amb_house":       dict(source="cc0", seconds=24.0, lufs=-30),
    "amb_attic":       dict(source="cc0", seconds=24.0, lufs=-29),
    "amb_night":       dict(source="cc0", seconds=24.0, lufs=-31),
    "amb_drips":       dict(source="cc0", seconds=24.0, lufs=-30),
    "raspberry_big":   dict(source="cc0", seconds=2.2, lufs=-17),
    "raspberry_small": dict(source="cc0", seconds=1.4, lufs=-22),

    # -- generated, because no Foley library has "the sound of a sound being taken" --
    "shloop": dict(
        source="gen", seconds=1.6, lufs=-19,
        prompt="a soft wet slurping swallow, like a sound being sucked into a jar, "
               "round and comical, not harsh, quick but smooth"),
    "shloop_soft": dict(
        source="gen", seconds=1.6, lufs=-24,
        prompt="a very soft, quiet wet slurping swallow, muted and distant, gentle"),
    "pop_cascade": dict(
        source="gen", seconds=5.0, lufs=-18,
        prompt="one glass pop, then two, then dozens cascading into a joyful rush of "
               "escaping sounds, rising steadily over four seconds, warm not harsh"),
}

# ── The book ──────────────────────────────────────────────────────────────────
# (block_id, kind, voice_or_sfx, text, pause_after, spread)
#
# `text` for speech blocks must match the player's visible text word-for-word once
# [tags] are stripped. tools/audit.py enforces this.

BLOCKS = [
    # ══ COVER ══
    ("cover_nar_01", "speech", "NARRATOR",
          "[warmly] The Hushabaloo. ... [whispers] Behind the third door on the left of the hall.", PAGE, "cover"),

    # ══ SPREAD 1 — a house that was full of it ══
    ("p1_nar_01", "speech", "NARRATOR",
          "[warmly] In a house at the end of a hall that was long, where the stairs had a squeak and the kettle a song, there was Etta, who planned. There was Mo, who could hear. There was Kip, who climbed everything, year after year.", LINE, "p1"),

    ("p1_sfx_creak", "sfx", "creak", "", LINE, "p1"),

    ("p1_nar_02", "speech", "NARRATOR",
          "[excited] And the house was so full of so much to be heard, of a clank and a clink and a creak and a bird, of the hum of the fridge, of the drip of the tap, of the whumpf of the dog as he flopped for a nap.", LINE, "p1"),

    ("p1_nar_03", "speech", "NARRATOR",
          "[curious] And the best of them all, and remember this trick, [whispers] was the door down the hall. And the door went...", LINE, "p1"),

    ("p1_sfx_click", "sfx", "click", "", BEAT, "p1"),

    ("p1_nar_04", "speech", "NARRATOR",      "[whispers] click.", PAGE, "p1"),

    # ══ SPREAD 2 — Tuesday ══
    ("p2_nar_01", "speech", "NARRATOR",
          "[curious] But on Tuesday the kettle did not sing its song. [sad] And the stairs did not squeak. And the tap-drip was gone.", SECTION, "p2"),

    ("p2_etta_01", "speech", "ETTA",
     "[curious] That's three. That's three sounds. And they've all gone away.", SECTION, "p2"),

    ("p2_nar_02", "speech", "NARRATOR",
          "[excited] Now the hall had three doors, and they knew one and two. But the third door, the third door they'd never been through. [whispers] And they stood there. And Mo put his ear to the wood.", SECTION, "p2"),

    ("p2_mo_01", "speech", "MO",
     "[whispers] Listen. ... Somefing in there.", SECTION, "p2"),

    ("p2_nar_03", "speech", "NARRATOR",
          "[curious] And there was. ... [excited] For a sound they had heard every day of their lives, the small squeak of the stairs, came unstuck, and it dived through the crack of that door with a...", LINE, "p2"),

    ("p2_sfx_shloop", "sfx", "shloop", "", BEAT, "p2"),

    ("p2_nar_04", "speech", "NARRATOR",
          "[whispers] and was gone. And the stairs were as silent as snow, from then on.", PAGE, "p2"),

    # ══ SPREAD 3 — a room that was not in the house ══
    ("p3_nar_01", "speech", "NARRATOR",
          "[whispers] So they opened the door, and the door made no sound, and they stepped through the door, and they looked all around. [curious] And behind the third door on the left of the hall was a room that was not in the house. Not at all.", LINE, "p3"),

    ("p3_nar_02", "speech", "NARRATOR",
          "[curious] It was tall as a church and as wide as a town, and it went up so far that no ceiling came down. And on every last shelf, in a row, in a row, were the jars. And each jar had a label. And so...", SECTION, "p3"),

    ("p3_etta_01", "speech", "ETTA",
     "[excited] That one's RAIN. That one's DOG. That one's stairs-when-you-creep. That one's somebody snoring. That's somebody's sheep!", SECTION, "p3"),

    ("p3_nar_03", "speech", "NARRATOR",
          "[whispers] Then a shelf became shoulders. A jar became eye. And the thing they'd been sure was a wall said...", SECTION, "p3"),

    ("p3_hush_01", "speech", "HUSHABALOO",
     "[excited] Oh. Hello. Oh my.", PAGE, "p3"),

    # ══ SPREAD 4 — the keeper ══
    ("p4_hush_01", "speech", "HUSHABALOO",
     "[warmly] I am only the keeper. I keep them. That's all. Every sound ever let loose in somebody's hall, every squeak, every drip, every creak, every knock, I have kept them all safe. Every one. Every clock.", SECTION, "p4"),

    ("p4_nar_01", "speech", "NARRATOR",
          "[curious] And he reached out a hand that was mostly a sleeve, and he took Kip's small laugh. And he did not ask leave.", LINE, "p4"),

    ("p4_sfx_shloop_1", "sfx", "shloop", "", LINE, "p4"),

    ("p4_nar_02", "speech", "NARRATOR",      "[whispers] And he took Mo's low hum.", LINE, "p4"),

    ("p4_sfx_shloop_2", "sfx", "shloop", "", LINE, "p4"),

    ("p4_nar_03", "speech", "NARRATOR",
          "[sad] And then, gentle and quick, he took Etta's own word, in the middle. Like this.", LINE, "p4"),

    ("p4_sfx_shloop_3", "sfx", "shloop", "", BEAT, "p4"),

    ("p4_nar_04", "speech", "NARRATOR",
          "[whispers] And behind them, so soft that not one of them heard, he reached out once again. And he took, from the door, [sad] the small click that it made.", LINE, "p4"),

    ("p4_sfx_shloop_4", "sfx", "shloop_soft", "", BEAT, "p4"),

    ("p4_nar_05", "speech", "NARRATOR",
          "[whispers] And the door was no more. ... For a door with no click isn't really a door. It's a wall. It's a wall. It's a wall. Nothing more.", PAGE, "p4"),

    # ══ SPREAD 5 — please ══
    ("p5_nar_01", "speech", "NARRATOR",
          "[warmly] Now Etta was five, which is old. And she knew that when somebody's taken a thing that's not theirs, you say give it back, please. So she said it. She did.", SECTION, "p5"),

    ("p5_etta_01", "speech", "ETTA",
     "Give them back. Give them back, please. They're ours.", SECTION, "p5"),

    ("p5_hush_01", "speech", "HUSHABALOO",
     "But they're safe. Don't you see? They are safe here with me. Nothing's lost. Nothing ever is lost here. Not one. I have rain from a Tuesday two hundred years gone. It's still raining. In there. It has never been done.", SECTION, "p5"),

    ("p5_etta_02", "speech", "ETTA",
     "But a sound isn't safe when it's kept in a...", LINE, "p5"),

    ("p5_sfx_shloop", "sfx", "shloop", "", BEAT, "p5"),

    ("p5_nar_02", "speech", "NARRATOR",
          "[curious] And the word that she needed went off in a jar. And she opened her mouth. ... [whispers] And there wasn't a sound.", PAGE, "p5"),

    # ══ SPREAD 6 — Kip climbs, because Kip climbs ══
    ("p6_nar_01", "speech", "NARRATOR",
          "[warmly] Then Kip sized the shelf up. Now, Kip is quite small. But of all of the things about Kip, above all...", LINE, "p6"),

    ("p6_kip_01", "speech", "KIP",
     "[whispers] I can get it.", LINE, "p6"),

    ("p6_nar_02", "speech", "NARRATOR",
          "Kip climbs. And Kip climbed. And Kip went up a shelf, and another, and up, and he leant", LINE, "p6"),

    ("p6_kip_02", "speech", "KIP",
     "[excited] Watch me! Watch me!", LINE, "p6"),

    ("p6_nar_03", "speech", "NARRATOR",
          "[excited] and he reached for a jar, and he stretched, and he wobbled, and grabbed, and...",
     LINE, "p6"),

    ("p6_kip_03", "speech", "KIP",
     "[excited] Uh oh.", LINE, "p6"),

    ("p6_sfx_pop", "sfx", "pop", "", LINE, "p6"),

    ("p6_sfx_rain", "sfx", "rain", "", LINE, "p6"),

    ("p6_nar_04", "speech", "NARRATOR",
          "[excited] And the jar came down hard, and the jar came apart, and out came the rain! All the rain! From the start! And it went up, and out, and it went through the wall, to the window it came from, right down the long hall.", SECTION, "p6"),

    ("p6_etta_01", "speech", "ETTA",
     "It went HOME. Did you see it? It broke and went home!", PAGE, "p6"),

    # ══ SPREAD 7 — the quiet part ══
    ("p7_nar_01", "speech", "NARRATOR",
          "[whispers] But the Hushabaloo sighed. And he lifted the shelf. And he put it up high, where a person can't climb. And he said it so softly, and mostly himself...", SECTION, "p7"),

    ("p7_hush_01", "speech", "HUSHABALOO",
     "[sad] Please don't break them. Please don't. I have had them a very long time.", SECTION, "p7"),

    ("p7_nar_02", "speech", "NARRATOR",
          "[whispers] And it got very dark. And it got very still. And the three of them sat. And they sat. And they sat. And there wasn't a squeak. And there wasn't a drip. And there wasn't a sound in the world. ... Just like that.", SECTION, "p7"),

    ("p7_sfx_roomtone", "sfx", "room_tone", "", BEAT, "p7"),

    ("p7_kip_01", "speech", "KIP",
     "[whispers] I want home.", LINE, "p7"),

    ("p7_mo_01", "speech", "MO", "[whispers] Me too.", SECTION, "p7"),

    ("p7_nar_03", "speech", "NARRATOR",
          "[warmly] And Etta, who's five, and who plans, and who's brave, [whispers] had no plan. And she said it out loud, very small...", LINE, "p7"),

    ("p7_etta_01", "speech", "ETTA",
     "I'm scared too.", SECTION, "p7"),

    ("p7_nar_04", "speech", "NARRATOR",
          "[excited] But then Mo, who hears things that the rest of us miss, [whispers] put his hand on a jar. And he listened. Like this.", SECTION, "p7"),

    ("p7_mo_02", "speech", "MO",
     "[whispers] Etta. ... This one empty.",
     SECTION, "p7"),

    ("p7_etta_02", "speech", "ETTA",
     "[curious] Empty? But he's got a jar for everything.", LINE, "p7"),

    ("p7_nar_05", "speech", "NARRATOR",
          "[excited] And Etta's eyes went round and wide.", LINE, "p7"),

    ("p7_etta_03", "speech", "ETTA",
     "[excited] He's got jars for the rain and the drip and the door, for the sounds that things MAKE. But he hasn't got more! He's got nothing at all for a sound that's not FOR anything! Nothing! He's not heard one before! ... Kip. Mo. On three. ... Do the rudest thing you know.", PAGE, "p7"),

    # ══ SPREAD 8 — the rudest thing they know ══
    ("p8_nar_01", "speech", "NARRATOR",
          "[excited] So Kip climbed. Because Kip climbs. And Mo found the jar, because Mo always finds them. That's just what Mo does. And Etta said...", LINE, "p8"),

    ("p8_etta_01", "speech", "ETTA", "[excited] THREE. TWO. ONE...", LINE, "p8"),

    ("p8_nar_02", "speech", "NARRATOR",
          "[excited] and the twins, who were two, did the one thing that two-year-old people do best.", 0.0, "p8"),

    ("p8_wait_01", "wait", "3.0", "", 0.0, "p8"),

    ("p8_kipmo_01", "speech", "KIP",
     "PBBBBBBBBT!", 0.0, "p8"),

    ("p8_sfx_raspberry", "sfx", "raspberry_big", "", BEAT, "p8"),

    ("p8_nar_03", "speech", "NARRATOR",
          "[excited] And it wasn't a squeak. And it wasn't a drip. And it wasn't the rain, and it wasn't a door. It was nothing! It meant nothing! It came from a lip and it went nowhere useful, a wonderful roar of a silly, wet, pointless, ridiculous noise that had no jar at all.", SECTION, "p8"),

    ("p8_nar_04", "speech", "NARRATOR",
          "[sad] And he looked for a jar. And he looked. And he looked. And he looked down the hall of ten thousand jars... [whispers] and there wasn't one. Not one. Not a label. Not one. Not at all. Not a jar.", BEAT, "p8"),

    ("p8_nar_05", "speech", "NARRATOR",
          "[whispers] And a thing with no jar is a thing you can't keep.", LINE, "p8"),

    ("p8_sfx_cascade", "sfx", "pop_cascade", "", LINE, "p8"),

    ("p8_nar_06", "speech", "NARRATOR",
          "[excited] And the empty jar popped. And the next. And the next. And the rain and the dog and the kettle and drip and the whumpf and the hum and the squeak of the stair went UP, and went OUT, and went HOME through the air.", PAGE, "p8"),

    # ══ SPREAD 9 — click ══
    ("p9_nar_01", "speech", "NARRATOR",
          "[whispers] And in all of that noise, in that whole rushing flood, there was one little sound that was smaller than most.", SECTION, "p9"),

    ("p9_mo_01", "speech", "MO",
     "Listen. ... There.", SECTION, "p9"),

    ("p9_nar_02", "speech", "NARRATOR",
          "[warmly] And Mo heard it. Of course. Because that's what Mo does. And he pointed. And there, in the dark, was a...", LINE, "p9"),

    ("p9_sfx_click", "sfx", "click", "", BEAT, "p9"),

    ("p9_nar_03", "speech", "NARRATOR",
          "[warmly] click. [excited] And a door with a click is a door once again.", SECTION, "p9"),

    ("p9_nar_04", "speech", "NARRATOR",
          "[warmly] But they stood in the doorway. And turned. And they saw that the Hushabaloo hadn't got anything more. [sad] He had shelves. He had jars. He had none of them full. And he sat down. And he was extremely small.", SECTION, "p9"),

    ("p9_etta_01", "speech", "ETTA", "Wait.", LINE, "p9"),

    ("p9_nar_05", "speech", "NARRATOR",
          "[whispers] And she walked all the way back, and stood by his knee.", LINE, "p9"),

    ("p9_etta_02", "speech", "ETTA",
     "[warmly] You can keep it. That one. That one's from me.", LINE, "p9"),

    ("p9_nar_06", "speech", "NARRATOR",
          "[warmly] And she blew him a raspberry, right through the air.", LINE, "p9"),

    ("p9_sfx_raspberry", "sfx", "raspberry_small", "", LINE, "p9"),

    ("p9_nar_07", "speech", "NARRATOR",
          "[warmly] And he caught it. And held it. And kept it. Right there. [whispers] And he put it in nothing. No jar and no lid. Just held it, which is, I suppose, what you do with a sound that was given and not taken. ... He did. And he smiled. If a Hushabaloo can. And he knew.", SECTION, "p9"),

    ("p9_nar_08", "speech", "NARRATOR",
          "[warmly] So they went down the hall to the house that was theirs, where the kettle had a song, and a squeak had the stairs, where the pipes gave a knock, and the tap gave a drip, and the dog gave a whumpf...", LINE, "p9"),

    ("p9_sfx_click_home", "sfx", "click", "", BEAT, "p9"),

    ("p9_nar_09", "speech", "NARRATOR",
          "[whispers] and the door gave a click.", PAGE, "p9"),

    # ══ FINAL ══
    ("final_nar_01", "speech", "NARRATOR",
          "[whispers] For everybody small who was ever once told to be quiet, be quiet, be quiet, be still... [warmly] here's a story where noise is the thing that saves all.", SECTION, "final"),

    ("final_nar_02", "speech", "NARRATOR",
          "[warmly] Go on. ... [curious] Make the sound. You know the one.",
     0.0, "final"),

    ("final_wait_01", "wait", "4.0", "", 0.0, "final"),

    ("final_sfx_raspberry", "sfx", "raspberry_big", "", PAGE, "final"),
]

# ── Participation ─────────────────────────────────────────────────────────────
# A `wait` block NEVER blocks. It pauses for its duration, then the story continues
# whether or not anyone made a sound. Two reasons, and they agree:
#
#   * House rule: the book auto-advances. It is never stuck waiting for input.
#   * Blue's Clues' pause is "long enough for the youngest, short enough for the
#     oldest," after which another voice supplies the answer anyway. See
#     research/01-developmental-psychology.md.
#
# So the 3s wait on spread 8 is followed by Kip and Mo doing it regardless -- the
# listeners are invited, never required, and never left hanging.

# ── Ambient beds ──────────────────────────────────────────────────────────────
# A quiet looping bed plays UNDER the narration for the whole spread, on its own
# channel, and cross-fades on the page turn. This is the immersion layer: the
# collection room should sound enormous and strange before anyone says it is.
#
# Levels are deliberately low. The research is explicit that a bed under speech
# hurts comprehension for two-year-olds specifically, whose auditory discrimination
# is still immature -- so these sit far enough down to be felt rather than heard,
# and spread 7 drops lower still because the story there IS the silence.
AMBIENCE = {
    "cover": None,
    "p1":    ("amb_house", 0.26),   # a house stuffed with noise
    "p2":    ("amb_house", 0.18),   # ...and quieter now, sounds going missing
    "p3":    ("amb_attic", 0.30),   # the collection: vast, strange, echoing
    "p4":    ("amb_attic", 0.30),
    "p5":    ("amb_attic", 0.26),
    "p6":    ("amb_drips", 0.28),   # rain loose in the room, heading home
    "p7":    ("amb_night", 0.13),   # the quietest thing in the book
    "p8":    ("amb_attic", 0.24),
    "p9":    ("amb_house", 0.26),   # home again -- the bed from spread 1 returns
    "final": ("amb_house", 0.16),
}

SPREADS = ["cover", "p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8", "p9", "final"]
